# ALL VALUES ARE PERCENTAGES
LEATHER:
  speed: 5
  projectile-damage-reduction: 10
  experience-gain: 5
  melee-damage: 0
  damage-reduction: 0
  fire-damage-reduction: 0
  explosion-damage-reduction: 0
  drop-chance: 0
  regeneration: 0
  max-health: 0

CHAIN:
  speed: 3
  melee-damage: 5
  damage-reduction: 5
  fire-damage-reduction: 10
  projectile-damage-reduction: 0
  experience-gain: 0
  explosion-damage-reduction: 0
  drop-chance: 0
  regeneration: 0
  max-health: 0

IRON:
  damage-reduction: 15
  melee-damage: 10
  fire-damage-reduction: 10
  experience-gain: 5
  max-health: 10
  speed: 0
  projectile-damage-reduction: 0
  explosion-damage-reduction: 0
  drop-chance: 0
  regeneration: 0

GOLD:
  speed: 15
  regeneration: 20
  drop-chance: 25
  projectile-damage-reduction: 0
  experience-gain: 0
  melee-damage: 0
  damage-reduction: 0
  fire-damage-reduction: 0
  explosion-damage-reduction: 0
  max-health: 0

DIAMOND:
  melee-damage: 15
  damage-reduction: 20
  fire-damage-reduction: 15
  explosion-damage-reduction: 20
  experience-gain: 10
  regeneration: 10
  max-health: 10
  speed: 0
  projectile-damage-reduction: 0
  drop-chance: 0

NETHERITE:
  melee-damage: 20
  damage-reduction: 30
  fire-damage-reduction: 25
  explosion-damage-reduction: 25
  experience-gain: 15
  regeneration: 15
  max-health: 25
  speed: 0
  projectile-damage-reduction: 0
  drop-chance: 0